'use strict';

/* ── MockData ────────────────────────────────────────────────── */
const MOCK_ROWS = [
  { match_id:'mock-1', kickoff_at:new Date(Date.now()+3_600_000).toISOString(),
    competition_code:'BUNDESLIGA', competition_name:'Bundesliga', league_abbr:'BL', flag:'🇩🇪',
    home_team:'Bayern München', away_team:'VfL Bochum', home_strength:98, away_strength:22,
    form_home:['W','W','W','D','W'], form_away:['L','L','D','L','L'],
    win_probability:81, draw_probability:11, away_probability:8,
    confidence_score:78, predicted_winner:'home', is_strong_tip:true, risk_level:'low', risk_tags:[],
    analysis_text:'Bayern München mit 81% klar favorisiert. Starker Tipp.',
    ai_reason:'Bayern liegt mit 76 Punkten Stärkeunterschied klar vorne. Exzellente Form mit 4 Siegen aus 5. Heimvorteil verstärkt den Vorteil.' },
  { match_id:'mock-2', kickoff_at:new Date(Date.now()+5_400_000).toISOString(),
    competition_code:'PREMIER_LEAGUE', competition_name:'Premier League', league_abbr:'PL', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    home_team:'Arsenal', away_team:'Manchester City', home_strength:82, away_strength:91,
    form_home:['W','D','W','W','L'], form_away:['W','W','W','D','W'],
    win_probability:31, draw_probability:23, away_probability:46,
    confidence_score:62, predicted_winner:'away', is_strong_tip:false, risk_level:'medium', risk_tags:['Ausgeglichene Stärke'],
    analysis_text:'Manchester City mit 46% Auswärtssieg leicht favorisiert.',
    ai_reason:'Manchester City mit 9 Punkten Stärkevorsprung. Bessere Tagesform. Knappe Entscheidung erwartet.' },
  { match_id:'mock-3', kickoff_at:new Date(Date.now()+7_200_000).toISOString(),
    competition_code:'LA_LIGA', competition_name:'La Liga', league_abbr:'LAL', flag:'🇪🇸',
    home_team:'Real Madrid', away_team:'Cádiz', home_strength:95, away_strength:18,
    form_home:['W','W','W','W','D'], form_away:['L','L','L','D','L'],
    win_probability:84, draw_probability:10, away_probability:6,
    confidence_score:82, predicted_winner:'home', is_strong_tip:true, risk_level:'low', risk_tags:[],
    analysis_text:'Real Madrid mit 84% klar favorisiert. Starker Tipp.',
    ai_reason:'Real Madrid dominiert mit 77 Punkten Stärkeunterschied. Nahezu makellose Heimform. Heimvorteil fließt zusätzlich ein.' },
  { match_id:'mock-4', kickoff_at:new Date(Date.now()+9_000_000).toISOString(),
    competition_code:'SERIE_A', competition_name:'Serie A', league_abbr:'SA', flag:'🇮🇹',
    home_team:'Juventus', away_team:'Inter Mailand', home_strength:74, away_strength:88,
    form_home:['D','W','L','W','D'], form_away:['W','W','D','W','W'],
    win_probability:28, draw_probability:27, away_probability:45,
    confidence_score:48, predicted_winner:'away', is_strong_tip:false, risk_level:'high', risk_tags:['Ausgeglichene Form','Wenig Datenbasis'],
    analysis_text:'Ausgeglichenes Derby: Juventus 28% – Remis 27% – Inter 45%.',
    ai_reason:'Inter Mailand leicht vorne mit 14 Punkten Stärkevorsprung. Typisches Derby-Spiel mit erhöhtem Risiko.' },
  { match_id:'mock-5', kickoff_at:new Date(Date.now()+10_800_000).toISOString(),
    competition_code:'LIGUE_1', competition_name:'Ligue 1', league_abbr:'L1', flag:'🇫🇷',
    home_team:'PSG', away_team:'Clermont Foot', home_strength:99, away_strength:12,
    form_home:['W','W','W','W','W'], form_away:['L','D','L','L','L'],
    win_probability:88, draw_probability:8, away_probability:4,
    confidence_score:89, predicted_winner:'home', is_strong_tip:true, risk_level:'low', risk_tags:[],
    analysis_text:'PSG mit 88% klar favorisiert. Starker Tipp.',
    ai_reason:'PSG liegt mit 87 Punkten Stärkeunterschied absolut dominant. Makellose Form (100%). Heimvorteil zusätzlich eingerechnet.' },
  { match_id:'mock-6', kickoff_at:new Date(Date.now()+14_400_000).toISOString(),
    competition_code:'CHAMPIONS_LEAGUE', competition_name:'Champions League', league_abbr:'UCL', flag:'🌍',
    home_team:'Atlético Madrid', away_team:'Borussia Dortmund', home_strength:null, away_strength:null,
    form_home:['W','L','W','D','W'], form_away:['D','W','L','W','W'],
    win_probability:44, draw_probability:24, away_probability:32,
    confidence_score:31, predicted_winner:'home', is_strong_tip:false, risk_level:'high', risk_tags:['Wenig Datenbasis','Ausgeglichene Form'],
    analysis_text:'Atlético mit 44% leicht favorisiert.',
    ai_reason:'Keine Standings-Daten für CL verfügbar. Formbasiert leicht für Atlético. Heimvorteil eingerechnet.' },
];

